#!/bin/sh
#
# name     : install-tmuxen, tmuxen install script
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# author   : CzBiX <gliuwr@gmail.com>
# license  : GPL
# created  : 2012 Jul 02
# modified : 2014 Jun 01
#

bin=$HOME/.local/bin
cwd=$(pwd)

if [ ! -d $bin ]; then
    mkdir $bin
fi

echo "Installing tmuxen to $bin"
ln -sf $cwd/tmuxen $bin/tmuxen

echo "Symlinking _tmux.conf to $HOME/.tmux.conf"
ln -sf $cwd/_tmux.conf $HOME/.tmux.conf

exit 0
